### ISSUE TITLE
get queens by name, rather then by id

### ISSUE THREAD

**Issue by calum** [GarrettLevine/drag-race-api#25]
It would be useful if we could query for a queens info using their name - the id is difficult to find.

GET `http://www.nokeynoshade.party/api/queens?name="Trixie Matel"`

example response:
```
  {
    "id":  "12",
    "name": 'Trixie Matel',
    "winner": false,
    "missCongeniality": false,
    "seasons": [
      {
        id: 1,
        place: 6,
      },
    ],
    "quote": 'Okay, calm down there public school.',
    "image_url": 'http://trixie-matel.com/213131.jpg',
  }
```

#### I am happy to work on this and submit a pull request. I wanted to check with you first.

Thanks,
Calum

**Comment by GarrettLevine** [comment]
hey @calum ! I have been wanting to write this for a bit so I am happy to prioritize it for you! Is there a deadline you wanted it completed by at all?

**Comment by GarrettLevine** [comment]
@calum I had some extra time this evening, and I was able to implement the change! I'll update the docs! 💃

**Comment by calum** [comment]
Thank you!
